fixtures:
  forge_modules:
    "augeas_core":
      "repo": "puppetlabs/augeas_core"
      "puppet_version": ">= 6.0.0"
    "mailalias_core":
      "repo": "puppetlabs/mailalias_core"
      "puppet_version": ">= 6.0.0"
  repositories:
    "augeas": "https://github.com/camptocamp/puppet-augeas.git"
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    "alternatives": "https://github.com/voxpupuli/puppet-alternatives.git"
  symlinks:
    "postfix": "#{source_dir}"
