---
.travis.yml:
  addons:
    apt:
      sources:
        - augeas
      packages:
        - libaugeas-dev
  branches:
    - master
    - /^\d/
  deploy_to_forge:
    enabled: true
    tag_regex: "^\\d"
  acceptance:
    - '*'
  user: camptocamp
  secure: "XAv4O363tng0KuRnu1ZhhwORy+2CF9UQwdwlFmS+NG9jOaTZZN+PMK8iC7OSIvZN6cfKlYjHRHNuxFBnYlnMrLsM9fVxt4NjjznOgIKQpQDleWk4UitZj5ntyHmUtYtofUd5Bhi/sdYXwGN9pVRCrcfFBmsIRq/dOhXD7Wy5KcQ="
  includes:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    - rvm: default
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=debian8-64{hypervisor=docker}
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
      stage: acceptance
    - rvm: default
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=debian9-64{hypervisor=docker}
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
      stage: acceptance
    - rvm: default
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=ubuntu1404-64{hypervisor=docker}
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
      stage: acceptance
    - rvm: default
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=ubuntu1604-64{hypervisor=docker}
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
      stage: acceptance
    - rvm: default
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=ubuntu1804-64{hypervisor=docker}
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
    - rvm: default
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=centos6-64{hypervisor=docker}
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
      stage: acceptance
    - rvm: default
      sudo: required
      services: docker
      env:
        - PUPPET_INSTALL_TYPE=agent
        - BEAKER_IS_PE=no
        - BEAKER_PUPPET_COLLECTION=puppet5
        - BEAKER_debug=true
        - BEAKER_setfile=centos7-64{hypervisor=docker}
      bundler_args:
      script: bundle exec rspec spec/acceptance/*_spec.rb
      stage: acceptance

Gemfile:
  required:
    ':development':
      - gem: ruby-augeas
    ':system_tests':
      - gem: beaker-hostgenerator
      - gem: "puppet-module-posix-system-r#{minor_version}"
  optional:
    ':development':
      - gem: 'github_changelog_generator'
Rakefile:
  changelog_version_tag_pattern: '%s'
